# Generated by Django 5.2 on 2025-08-10 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_served',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
