# Generated by Django 5.2 on 2025-08-16 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_date_served'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('budgetedExpense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actualExpense', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField()),
                ('weekEnd', models.DateField()),
                ('mealDate', models.DateField()),
                ('mealType', models.CharField(choices=[('O', 'Breakfast'), ('M', 'Lunch'), ('A', 'Dinner'), ('N', 'Night Snack')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('mealCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RationAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('min_Allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_Allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualUsage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('categoryName', models.CharField(max_length=100)),
                ('rationGroupNo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='fooditemusage',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='menu',
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('totalMeals', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.meals')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('totalFeeding', models.IntegerField()),
                ('totalExpenditure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totalRations', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annualSummaries', to='core.expenses')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annualSummaries', to='core.monthlysummary')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annualSummaries', to='core.rationallowance')),
            ],
        ),
        migrations.AddField(
            model_name='rationallowance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rationAllowances', to='core.stockcategory'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.stockcategory'),
        ),
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stockcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField()),
                ('weekEnd', models.DateField()),
                ('startStock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('externalIssues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endStock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.stockitems')),
            ],
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='FoodItemUsage',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='InventoryTransaction',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
