# Generated by Django 5.2 on 2025-08-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expenses_meals_rationallowance_stockcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='mealType',
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealCategory',
            field=models.CharField(choices=[('O', 'Breakfast'), ('M', 'Lunch'), ('A', 'Dinner'), ('N', 'Night Snack')], max_length=20),
        ),
    ]
