# Generated by Django 5.2 on 2025-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_meals_mealtype_alter_meals_mealcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='mealsFor_A',
            field=models.CharField(choices=[('staff', 'Staff'), ('creche', 'Creche'), ('breastfeeding', 'Breastfeeding'), ('kangaroo', 'Kangaroo'), ('outpatients', 'Outpatients'), ('travelling', 'Travelling Patients'), ('other', 'Other Meals (Specify)')], default='staff', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meals',
            name='mealsFor_B',
            field=models.CharField(blank=True, choices=[('full_meals', 'Full Meals'), ('therapeutic', 'Therapeutic'), ('private', 'Private Patients'), ('infants_toddlers', 'Infants / Toddlers')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='mealsFor_C',
            field=models.CharField(blank=True, choices=[('tube_feeds', 'Tube Feeds'), ('milk_feedings', 'Infants - Milk Feedings')], max_length=50, null=True),
        ),
    ]
