# Generated by Django 5.2 on 2025-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meals_mealsfor_a_meals_mealsfor_b_meals_mealsfor_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='mealCategory',
            field=models.CharField(choices=[('O(Breakfast)', 'Breakfast'), ('M(Lunch)', 'Lunch'), ('A(Dinner)', 'Dinner'), ('N(Night Snack)', 'Night Snack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealsFor_A',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('creche', 'Creche'), ('breastfeeding', 'Breastfeeding'), ('kangaroo', 'Kangaroo'), ('outpatients', 'Outpatients'), ('travelling', 'Travelling Patients'), ('other', 'Other Meals (Specify)')], max_length=50, null=True),
        ),
    ]
