# Generated by Django 5.2 on 2025-08-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_meals_mealcategory_alter_meals_mealsfor_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysummary',
            name='meal',
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealCategory',
            field=models.CharField(choices=[('O', 'Breakfast'), ('M', 'Lunch'), ('A', 'Dinner'), ('N', 'Night Snack')], max_length=20),
        ),
    ]
