# Generated by Django 5.2.5 on 2025-08-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_monthlysummary_meal_alter_meals_mealcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='mealsFor_A',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='mealsFor_B',
        ),
        migrations.RemoveField(
            model_name='meals',
            name='mealsFor_C',
        ),
        migrations.AddField(
            model_name='meals',
            name='mealsFor',
            field=models.CharField(choices=[('staff', 'Staff'), ('creche', 'Creche')], default='staff', max_length=50),
            preserve_default=False,
        ),
    ]
