# Generated by Django 5.2.5 on 2025-08-31 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_meals_mealsfor_a_remove_meals_mealsfor_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_no', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.AlterUniqueTogether(
            name='monthlysummary',
            unique_together={('month', 'year')},
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_issued', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extern_issues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stockitem')),
            ],
        ),
        migrations.DeleteModel(
            name='StockItems',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
