# Generated by Django 5.2.5 on 2025-09-04 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_remove_stockmovement_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Meal Recipient',
                'verbose_name_plural': 'Meal Recipients',
            },
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealsFor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mealrecipient'),
        ),
    ]
