# Generated by Django 5.2.5 on 2025-10-17 01:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mealrecipient_alter_meals_mealsfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annual_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week1_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week2_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week3_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week4_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('week5_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_g_entries', to='core.stockcategory')),
            ],
            options={
                'ordering': ['-year', '-month', 'category__categoryName'],
                'unique_together': {('category', 'month', 'year')},
            },
        ),
    ]
