# Generated by Django 5.2.5 on 2025-10-19 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_formg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formg',
            options={'ordering': ['-year', '-month', 'category__description']},
        ),
        migrations.RemoveField(
            model_name='rationallowance',
            name='actualUsage',
        ),
        migrations.RemoveField(
            model_name='rationallowance',
            name='max_Allowance',
        ),
        migrations.RemoveField(
            model_name='rationallowance',
            name='min_Allowance',
        ),
        migrations.RemoveField(
            model_name='rationallowance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='rationallowance',
            name='year',
        ),
        migrations.AddField(
            model_name='rationallowance',
            name='per',
            field=models.CharField(default='day', max_length=20),
        ),
        migrations.AddField(
            model_name='rationallowance',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.category'),
        ),
        migrations.AlterField(
            model_name='formg',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_g_entries', to='core.category'),
        ),
        migrations.AlterField(
            model_name='rationallowance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.CreateModel(
            name='FormH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('week1_usage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('week2_usage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('week3_usage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('week4_usage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('week5_usage', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_usage', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('avg_per_person_per_day', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'unique_together': {('category', 'month', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='AnnualSummary',
        ),
        migrations.AddField(
            model_name='rationallowance',
            name='max_allowance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationallowance',
            name='min_allowance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
