# Generated by Django 4.2 on 2025-10-21 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_formg_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCategory',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_no'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-year', '-month', 'category'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='formg',
            options={'ordering': ['-year', '-month', 'category__description'], 'verbose_name': 'Form G', 'verbose_name_plural': 'Form G Entries'},
        ),
        migrations.AlterModelOptions(
            name='formh',
            options={'ordering': ['-year', '-month', 'category'], 'verbose_name': 'Form H', 'verbose_name_plural': 'Form H Entries'},
        ),
        migrations.AlterModelOptions(
            name='mealrecipient',
            options={'ordering': ['name'], 'verbose_name': 'Meal Recipient', 'verbose_name_plural': 'Meal Recipients'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'ordering': ['-mealDate', 'mealsFor'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='monthlysummary',
            options={'ordering': ['-year', '-month'], 'verbose_name_plural': 'Monthly Summaries'},
        ),
        migrations.AlterModelOptions(
            name='rationallowance',
            options={'verbose_name_plural': 'Ration Allowances'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='weeklystockmovement',
            options={'ordering': ['-week_number', 'stock_item']},
        ),
        migrations.AddField(
            model_name='stockitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='weeklystockmovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='totalMeals',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rationallowance',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterUniqueTogether(
            name='expenses',
            unique_together={('month', 'year', 'category')},
        ),
        migrations.AddIndex(
            model_name='meals',
            index=models.Index(fields=['mealDate', 'mealsFor'], name='core_meals_mealDat_463da2_idx'),
        ),
        migrations.AddIndex(
            model_name='meals',
            index=models.Index(fields=['weekStart', 'weekEnd'], name='core_meals_weekSta_83c2da_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['category', 'is_active'], name='core_stocki_categor_2c220e_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklystockmovement',
            index=models.Index(fields=['week_number', 'stock_item'], name='core_weekly_week_nu_029372_idx'),
        ),
    ]
