# Generated by Django 4.2 on 2025-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_stockcategory_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('total_meals_served', models.IntegerField(default=0)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_cost_per_meal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Annual Summaries',
                'ordering': ['-year'],
            },
        ),
    ]
