# Generated by Django 4.2 on 2025-10-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_annualsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklystockmovement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='weeklystockmovement',
            name='core_weekly_week_nu_029372_idx',
        ),
        migrations.AddField(
            model_name='weeklystockmovement',
            name='end_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklystockmovement',
            name='start_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklystockmovement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
